### ISSUE TITLE
put our documentation on 'readthedocs'

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#100]
By now it is expected that any non-trivial open source project has its documentation in readthedoc.io. We need to migrate our user- and reference-guides to that website.

**Comment by TimColaneri** [comment]
Asteroid now has its documentation hosted on 'readthedocs'.

https://asteroid-lang.readthedocs.io/en/latest/

The files that this documentation is built off of can be found in the /docs/ folder of the asteroid repository.
