### ISSUE TITLE
List comprehensions do not automatically detect descending lists

### ISSUE THREAD

**Issue by olwmc** [asteroid-lang/asteroid#122]
Lists comprehensions of the form `X to Y` do not automatically adjust the `step` value when `X > Y`.

Example:
```
let x = [5 to 0].  -- Returns an empty list
```

**Comment by olwmc** [comment]
I'm wondering what would actually be the best syntax here. Although I think that something like `[5 to 1 step -1]` is natural for a programmer, now that I look at it a little closer it's kind of strange. IMO "Step" refers to the size of the jump, not the direction. The direction of the jump is implied if you're going *from* X to Y. 

This is all to say, should negative values even be allowed for a step? I might just be thinking a little off about this.

**Comment by olwmc** [comment]
Should users have to specify a negative step for something like `[5 to 0 step 2]`? The direction of the step is already implied by the bounds of the range so I'm wondering if we should even support negative step values at all.

**Comment by lutzhamel** [comment]
So I took a peek how Python thinks about this.  Doing help on the `range` object gives us:
```
class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
```
Notice the terminology.  Here is an example,
```
>>> l = [i for i in range(10,0,-1)]
>>> l
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
```
So the increments of access are called 'step' and they can be negative!

The Asteroid analog is,
```
let l = [10 to 1 step -1].
io @println l.
```

**Comment by lutzhamel** [comment]
@olwmc The more I think about it the more I like your idea that step values should never be negative.  Steps are just describe a stride value...actually, should we call it `stride`?

So then your expression from above becomes,
```
[5 to 0 stride 2]
```
giving us,
```
[5,3,1]
```
I also think incorrectly specified list comprehensions should never fail silently like,
```
>>> list(range(5,0,2))
[]
>>>
```
They should produce either a warning or an error.

**Comment by olwmc** [comment]
Yes! Exactly what I was thinking. I can work on this very soon.

**Comment by olwmc** [comment]
Started. Work is now being done on the tik-122 branch
