### ISSUE TITLE
misleading error messages

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#126]
The following program,
```
load system io.

let x = 1
io @println "hello".
```
generates the error,
```
Error: apply-error.ast: 3: unknown apply term 'integer'
```
This is due to the fact of the missing `.` after the `let` statement making this statement 
actually look like,
```
let x = 1 io @println "hello".
```
Since function application is defined by juxtaposition the term
```
1 io
```
looks like the function application 
```
1(io)
```
which does not make any sense.  I suggest that we amend this error message to state this,
```
Error: apply-error.ast: 3: unknown apply term 'integer', perhaps an end-of-line period is missing,
```
Are there other error messages that could be improved?

**Comment by olwmc** [comment]
`none of the function bodies unified with actual parameters` could be changed to something more new user friendly like `actual argument not recognized.`

Reference [#142 Reply from lutzhamel](https://github.com/asteroid-lang/asteroid/issues/142#issuecomment-1051123744)
