### ISSUE TITLE
Test suite run before pull requests are merged

### ISSUE THREAD

**Issue by olwmc** [asteroid-lang/asteroid#128]
It would be nice to use the github actions/workflows feature to have tests automated before a pull request is merged. That way we can't accidentally forget it.

**Comment by olwmc** [comment]
The page for github actions is linked [here](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions). If you folks are interested in using it, I'd be happy to work it out for asteroid. I used them for my CSC305 project and it saved quite a lot of headache.

**Comment by lutzhamel** [comment]
That would be awesome.  I had looked at actions briefly but did not strike me as straightforward so I gave up on it again.  I think we should set up actions for
1. running the testsuite
2. generating the docs (so that the docs will always have the latest code snippets)

**Comment by olwmc** [comment]
Great! I'll work on this.

**Comment by olwmc** [comment]
This is being worked on (here)[https://github.com/asteroid-lang/asteroid/tree/workflow]
