### ISSUE TITLE
redundancy checker does not recognize %pattern properly

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#145]
With patterns as true values the redundancy checker does not properly deal with the following program,
```
load system io.

function foo
    with %pattern do
        io @println("is a pattern").
    with _ do
        io @println("not a pattern").
    end

foo (pattern x, pattern y).
foo (lambda with x do return x).
```
generates the following error,
```
Error:  Redundant Pattern Detected
	Function: foo from file pattern4.ast
	Pattern: %pattern on line 4
	will consume all matches for
	Pattern: _ on line 6
```
But this is incorrect because functions are not patterns and functions are matched by `_`.  Actually, the bug goes deeper, the following program also does not work,
```
load system io.

function foo
    with %pattern do
        io @println("is a pattern").
    with %function do
        io @println("not a pattern").
    end

foo (pattern x, pattern y).
foo (lambda with x do return x).
```
generates the error,
```
Error:  Redundant Pattern Detected
	Function: foo from file pattern4.ast
	Pattern: %pattern on line 4
	will consume all matches for
	Pattern: %function on line 6
```
which is clearly not true since patterns are not functions.

**Comment by TimColaneri** [comment]
Addressed with PR 150.

The pattern type-pattern is now recognized and behaves correctly.

**Comment by TimColaneri** [comment]
Addressed with PR 150.

The pattern type-pattern is now recognized and behaves correctly.
