### ISSUE TITLE
Creating Quick Start Guide/Tutorial

### ISSUE THREAD

**Issue by christian7974** [asteroid-lang/asteroid#161]
Add a quick start guide/tutorial for new users of Asteroid in restructured text. I have not used restructured text before so I will learn it this weekend and get that done. I plan on talking about pattern matching, what it is, why it is useful and want to emphasize the difference between pattern matching and other programming paradigms.

**Comment by christian7974** [comment]
*I want to try to assign myself to this, however I am unable to press on assignee or any of the settings on the right side*.

**Comment by lutzhamel** [comment]
@christian7974 You are all set.  I will make you a contributor so you have access to features like these.

Also be aware that all our new development is being deployed into the dev-1.0.0 branch.

Thanks for taking this on!
