### ISSUE TITLE
REPL variable content printed in incorrect format

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#171]
In the REPL variable content is printed in the incorrect format, e.g.
```
Asteroid Version 1.0.0
Run "asteroid -h" for help
Press CTRL+D to exit
> let l = 0 to 4.
> l
[('integer', 0), ('integer', 1), ('integer', 2), ('integer', 3), ('integer', 4)]
> 
```
The value stored in `l` should be converted to a printable string with `term2string` instead of dumping the raw value component  of an Asteroid value to the terminal.

**Comment by olwmc** [comment]
Ahh! Nice catch. I'll get on this

**Comment by lutzhamel** [comment]
👍
