### ISSUE TITLE
command line switch not recognized without filename present

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#188]
The asteroid interpreter does not recognize command line switches if there is no input file present, e.g.
```
lutz$ dbgasteroid -F
unknown file -F
```
but
```
lutz$ dbgasteroid -F break.ast 
error: break.ast: 5: loop is not supported in functional mode
lutz$
```

**Comment by olwmc** [comment]
Should we try out the standard python library for this sort of thing?

https://docs.python.org/3/library/argparse.html

**Comment by lutzhamel** [comment]
No, I don't like that thing, I have tried it in the past and it completely enforces whatever policy its designers had in mind and allows for nothing else.

**Comment by olwmc** [comment]
Fair!
