### ISSUE TITLE
ADB should also support a single character flag for the debugger: perhaps -g?

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#193]
ADB should also support a single character flag for the debugger: perhaps -g?

**Comment by olwmc** [comment]
To clarify, you you mean using both -g and the current --adb, or solely -g. I originally had --adb just so that I could search my command history easier

**Comment by lutzhamel** [comment]
The accepted idea is that if you introduce double dash switches there there is always a single letter switch that also accomplished the same thing.  So in this case '-g' and '--adb' both do the same thing.

**Comment by olwmc** [comment]
An implementation is now up on the PR. `-g` and `--adb` are both supported.

**Comment by lutzhamel** [comment]
@olwmc Excellent!  One more nitpicky thing.  Could you add descriptions of those switches to the `display_help()` function?

**Comment by olwmc** [comment]
How's this? It seems to be standard to level them out in this way.
```
** Asteroid Version 1.1.0 **
(c) University of Rhode Island
usage: asteroid [-<switch>] <input file>

command line flags:
 -s          enable symbol table dump
 -t          AST dump
 -v          version
 -w          disable tree walk
 -z          generate pstats
 -p          disable prologue
 -h          display help
 -r          disable redundant pattern detector
 -e          show Python exceptions
 -F          functional mode
 -g, --adb   run program through debugger
```

**Comment by olwmc** [comment]
This has also been fixed. Will close when PR is merged

**Comment by olwmc** [comment]
Ahh that makes sense. Alright. I’ll push that when I get home. I have the
changes lined up.
