### ISSUE TITLE
ADB needs to support interpreter mode flags

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#194]
ADB needs to support interpreter mode flags
```
if flags['--adb']:
        db = adb.ADB()
        db.run(input_file) # need to pass mode flags to interpreter
        sys.exit(0)
```
This is also true for the embedded call to the repl.  

See the following code snippet for ideas,
```
        repl(redundancy=flags['-r'],
             prologue=flags['-p'],
             functional_mode=flags['-F'])
```

**Comment by olwmc** [comment]
To be clear, which ones are we looking to support?

`functional_mode`, `prologue`, and `redundancy` seem obvious. What would we want `exceptions` to do here? Similarly with `symtab_dump`? I imagine we don't want to support `do_walk=False`.

It seems to make sense that we just keep the runtime affecting flags. Meaning `prologue`, `functional_mode`, `exceptions`, and `redundancy`. I could also see the case for `tree_dump` but `do_walk=False` I don't feel makes any sense.

**Comment by olwmc** [comment]
After some tinkering, `exceptions` could probably just work like an extended error message. Sort of like how you would expect it to work in the normal interpreter.

Here's a truncated example of what I mean:
```
ERROR: /home/oliver/test.ast: 7: 'A' is not defined
Traceback (most recent call last):
  File "/home/oliver/dev/asteroid/asteroid/adb/adb.py", line 193, in run
    interp(input_stream,
  ...
  ...
  ...
  File "/home/oliver/dev/asteroid/asteroid/symtab.py", line 77, in lookup_sym
    raise ValueError("'{}' is not defined".format(sym))
ValueError: 'A' is not defined

    ==>> let *p = B(1,2).
```

**Comment by lutzhamel** [comment]
> To be clear, which ones are we looking to support?
> 
> `functional_mode`, `prologue`, and `redundancy` seem obvious. What would we want `exceptions` to do here? Similarly with `symtab_dump`? I imagine we don't want to support `do_walk=False`.
> 
> It seems to make sense that we just keep the runtime affecting flags. Meaning `prologue`, `functional_mode`, `exceptions`, and `redundancy`. I could also see the case for `tree_dump` but `do_walk=False` I don't feel makes any sense.

Please take a look at the repl implementation in the interpreter.  I would expect those three flags to be supported.

**Comment by olwmc** [comment]
Ahh alright. Sure. I’ll just mirror that.

**Comment by lutzhamel** [comment]
> After some tinkering, `exceptions` could probably just work like an extended error message. Sort of like how you would expect it to work in the normal interpreter.
> 
> Here's a truncated example of what I mean:
> 
> ```
> ERROR: /home/oliver/test.ast: 7: 'A' is not defined
> Traceback (most recent call last):
>   File "/home/oliver/dev/asteroid/asteroid/adb/adb.py", line 193, in run
>     interp(input_stream,
>   ...
>   ...
>   ...
>   File "/home/oliver/dev/asteroid/asteroid/symtab.py", line 77, in lookup_sym
>     raise ValueError("'{}' is not defined".format(sym))
> ValueError: 'A' is not defined
> 
>     ==>> let *p = B(1,2).
> ```

Hmmm, you folded a different discussion into this bug report.  In any case.  Just try the interpreter and see what it does: it will trap the exceptions and will not show you Python stuff but if you enable `-e` then it will show you the whole ugly truth.

By default Asteroid should never expose Python level stuff.

**Comment by lutzhamel** [comment]
👍

**Comment by olwmc** [comment]
This is fixed and part of the new PR
