### ISSUE TITLE
exit does not print message when given a message string

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#232]
The code
```
load system os.
os @exit "all done".
```
does not print all done.  Do we need to flush the output?

**Comment by SupurCalvinHiggins** [comment]
The SystemExit exception is being caught by the interpreter which then calls `exit(0)`. The offending code is in interp.py.

**Comment by lutzhamel** [comment]
Nice find.  It is probably true that exit codes do not work correctly as well.  The fix might be to catch the SystemExit exceptions specifically and rethrow them so they percolate up to the system level.
