### ISSUE TITLE
Fatal bug in Windows interpreter when using a clean installation of python

### ISSUE THREAD

**Issue by carlstoker** [asteroid-lang/asteroid#233]
The interpreter shell was changed to use pyreadline3 instead of readline in PR #204:

https://github.com/asteroid-lang/asteroid/blob/607c096d2225ac76da73b6d791427b7ca4add0a7/asteroid/repl.py#L17-L20

However, this package is not included by default in a new python installation, nor is it installed when installing asteroid-lang via pip. This causes the interpreter to crash with a fatal error upon execution:
![image](https://user-images.githubusercontent.com/40079934/215365952-ef28a96a-fca9-4d95-b211-d9eeb59d51d2.png)

I'll be making a pull request which will add a line to requirements.txt to install pyreadline3 where platform_system is Windows.

I believe this may fix the issue, though I'm not familiar with how pypi is compiling the interpreter.

**Comment by olwmc** [comment]
This was solved by Carl's recent PR
