### ISSUE TITLE
The 'type' module should not be imported into the 'io' module at the global level

### ISSUE THREAD

**Issue by TimColaneri** [asteroid-lang/asteroid#235]
Currently, the `type` module is imported into the `io` module at the global level. This can cause namespace clashes. 

The type module should be imported at the `__IO_MODULE__` structure level.

The following code snippet generates an error due to this issue:
```
load system io.

let type = 1.

io@ println "Hello World!"
```

**Comment by lutzhamel** [comment]
There is no more type module in the 2.0 type system
