### ISSUE TITLE
Issue warning when detecting chained relational operators

### ISSUE THREAD

**Issue by carlstoker** [asteroid-lang/asteroid#236]
When evaluating a statement containing chained comparisons such as `a < b < c`, I would expect a language to either evaluate it as `(a < b) and (b < c)` or to fail to compile/run. Right now, asteroid seems to be evaluating the left as true (1) and then comparing it to the next operand. Here is `1 < 50 < 10` as an example:
```
ast> 1<50
true
ast> 50<10
false
ast> 1<50<10
true
ast> (1 < 50) and (50 < 10)
false
```
Showing that it evaluates as 1 (true):
```
ast> 1 < 50 < 2
true
ast> 1 < 50 < 1
false
ast> 1 < 50 == 1
true
```

For comparison, here is python evaluating it as `(1 < 50) and (50 < 10)`
```
>>> 1 < 50
True
>>> 50 < 10
False
>>> 1 < 50 < 10
False
```

Here is Rust failing to compile:
```
error: comparison operators cannot be chained
 --> src\main.rs:3:15
  |
3 |     let x = 1 < 5 < 10;
  |               ^   ^
  |
help: split the comparison into two
  |
3 |     let x = 1 < 5 && 5 < 10;
  |                   ++++

error: could not compile `comparison` due to previous error
```

Note: C and C++17 evaluate it the same way, which may cause undesired and unexpected behavior.

**Comment by lutzhamel** [comment]
Asteroid's interpretation of relational operators works exactly the way they work in Python except that Python interprets relational operators as right-associative where Asteroid interprets them as left-associative.
Python:
```
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 < (50 < 10)
False
>>> (1<50)<10
True
>>>
```

Asteroid:
```
Asteroid Version 1.1.4
(c) University of Rhode Island
Type "asteroid -h" for help
Press CTRL-D to exit
ast> 1 < (50 < 10)
false
ast> (1<50)<10
true
ast>
```

**Comment by carlstoker** [comment]
Python seems to be left associative as well, but expands `a < b < c` to something approximating `(a < b) and (b < c)` (while only evaluating b once).

If I write this function in python: 
```python
def comp():
    return 1 < 50 < 10
```
this is what it disassembles to: 
```
  2           0 LOAD_CONST               1 (1)
              2 LOAD_CONST               2 (50)
              4 DUP_TOP
              6 ROT_THREE
              8 COMPARE_OP               0 (<)
             10 JUMP_IF_FALSE_OR_POP     9 (to 18)
             12 LOAD_CONST               3 (10)
             14 COMPARE_OP               0 (<)
             16 RETURN_VALUE
        >>   18 ROT_TWO
             20 POP_TOP
             22 RETURN_VALUE
```

This is different from how python compiles `1 < (50 < 10)` to bytecode:
```python
def comp():
    1 < (50 < 10)
```
```
  1           0 LOAD_CONST               1 (1)
              2 LOAD_CONST               2 (50)
              4 LOAD_CONST               3 (10)
              6 COMPARE_OP               0 (<)
              8 COMPARE_OP               0 (<)
             10 POP_TOP
             12 LOAD_CONST               0 (None)
             14 RETURN_VALUE
```

Python is evaluating left-to-right, but is doing some tricks with the stack (duplicating the top of the stack and then rotating before doing comparisons) to allow chaining of operators. This behavior continues with 4 or more chains. 
 
#
`asteroid -t` generates the following AST for `let result = 1 < 50 < 10.`:
<details><summary>Asteroid AST</summary>

```
(list
  |[
  |  |(lineinfo
  |  |  |(comp.ast 1))
  |  |(unify
  |  |  |(id result)
  |  |  |(apply
  |  |  |  |(id __lt__)
  |  |  |  |(tuple
  |  |  |  |  |[
  |  |  |  |  |  |(apply
  |  |  |  |  |  |  |(id __lt__)
  |  |  |  |  |  |  |(tuple
  |  |  |  |  |  |  |  |[
  |  |  |  |  |  |  |  |  |(integer 1)
  |  |  |  |  |  |  |  |  |(integer 50)]))
  |  |  |  |  |  |(integer 10)])))])
```
</details>

### Chaining equality statements

#### Python
```
>>> 0 == 0 == 0
True
>>> 1 == 1 == 1
True
```

#### Asteroid
```
ast> 0 == 0 == 0
false
ast> 1 == 1 == 1
true
```

### Code with side effects
Another example can be shown by writing functions with side effects and seeing in which order they evaluate.

#### Python
```python
def n1():
    print("evaluating n1()")
    return 1
    
def n50():
    print("evaluating n50()")
    return 50
    
def n10():
    print("evaluating n10()")
    return 10
    
print(n1() < n50() < n10())
```
which prints 
```
evaluating n1()
evaluating n50()
evaluating n10()
False
```

#### Asteroid
```
load system io.

function n1
    with none do
		io @println "evaluating n1".
		return 1.
end

function n50
    with none do
		io @println "evaluating n50".
		return 50.
end

function n10
    with none do
		io @println "evaluating n10".
		return 10.
end

io @println (n1() < n50() < n10()).
```
which prints
```
evaluating n1
evaluating n50
evaluating n10
true
```

**Comment by lutzhamel** [comment]
Interesting, I just took a look at the Python spec [comparison expressions](https://docs.python.org/3/reference/expressions.html#comparisons)

According to this the semantics of an expression of the form
```
a relop1 b relop2 c
```
is 
```
a relop1 b and b relop2 c
```
I find this to be extremely non-intuitive and does not derive from the semantics of the operators.  This means for example that the interpretation of the expression based on the semantics of the operators
```
a + b + c
```
is completely different from the interpretation of 
```
a < b < c
```
which now acquires an interpretation which cannot be derived directly from the interpretation of the individual operators, ie, it acquires the interpretation 
```
a < b and b < c
```
instead of the inferred interpretation
```
(a < b) < c
```
I am firmly in the camp of Rust/C/C++ in that the interpretation of a composite expression must be based the straight forward interpretation of the individual operators.

I could see Asteroid issuing a warning a la Rust as to chaining of relops but I think the semantics as they stand are sound, just different from Python.

**Comment by lutzhamel** [comment]
The new type system in 2.0 does not allow for relational operations to be applied to Booleans.
