### ISSUE TITLE
The __str__ function for structures

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#24]
The idea is to give users the ability to represent objects as strings for printing purposes for example. Given the following code,
```
load system io.

structure Foo with
     data a.
     data b.
     function __str__ with none do return "Foo with " + this @a + " and " + this @b end.
     end

let o = Foo(1,2).
io @println o.
```
Here `println` would automatically invoke the` __str__` function (if it exists) in order to print out the object `o`. The output would be,
```
Foo with 1 and 2
```

**Comment by olwmc** [comment]
Under the hood would we want something similar to python's `str` function? We could very easily match `type @tostring` to match.

**Comment by lutzhamel** [comment]
@SupurCalvinHiggins This issue is assigned to you but there hasn't been any activity since Feb.  Are you still planning on working on this for the summer release?  Thanks, Lutz

**Comment by lutzhamel** [comment]
Not a critical feature.  Pushing back to another release.
