### ISSUE TITLE
Redundant Pattern Detector: headtail patterns  

### ISSUE THREAD

**Issue by TimColaneri** [asteroid-lang/asteroid#247]
Non-redundant headtail patterns are incorrectly recognized as redundant in the case when a more specific tail pattern breaks the subsumption. As an example, the following program incorrectly raises a redundant pattern exception... 

```
load system io.
load system math.

function lhs_exp
  with [] do
    1
  with [ value | [] ] do
    value
  with [ value | tail ] do
    math@pow( lhs_exp tail, value)
end

let x = [2,3,4].
io@println( lhs_exp x ).
```
... as shown here ...
```
error: CSC493/programs/x.ast: 14: Redundant Pattern Detected
    Function: lhs_exp from file CSC493/programs/x.ast
    Pattern: [value|[]] on line 7
    will consume all matches for
    Pattern: [value|tail] on line 9
```

**Comment by lutzhamel** [comment]
after code renovation of unify head-tail is no longer supported by redundancy checking (#266)
