### ISSUE TITLE
add 'round' function to math module

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#262]
add 'round' function to math module so that something like this will work,
```
load system math.

assert (math @round 19.6 == 20).
assert (math @round 19.2 == 19).
```

**Comment by lutzhamel** [comment]
@ijchen Perfect! I would like to stick to the mathematical definition of ceil/floor/round where these functions always return an integer.  If you do decide to take this on please create a branch off branch dev-2.0.1 which is our current development branch for the next release.  Also, before you create a pull request for your changes make sure that you update the documentation and generate new docs and run the test suites.  You should probably also assign this to yourself so that it is clear that you are working on it.

If you like I can also add you to our Asteroid Slack channel.

Any questions, just give me a holler!

**Comment by ijchen** [comment]
@lutzhamel Sounds good, and I'll make sure to branch off `dev-2.0.1`.

I don't see a way to assign myself - do I have permission to do so?

Yes, please add me to the Asteroid Slack. I actually do have a question so that would be helpful. My slack email is `ijchen@uri.edu`
