### ISSUE TITLE
Windows still needs pyreadline3 after pip install

### ISSUE THREAD

**Issue by davidhbrown-uri** [asteroid-lang/asteroid#297]
After `pip install asteroid-lang` on a Windows system, attempting to start asteroid reports `ModuleNotFoundError: No module named 'pyreadline3'`. @lutzhamel believes it may need to be added to `setup.py` as well as having already been added to `requirements.txt`.

**Comment by TimColaneri** [comment]
Hey @davidhbrown-uri ! Long time no see, I took 301 and 305 with you a few years ago!

It looks like the method of how Python software packages should specify what their build dependencies are has changed with [PEP 517/518](https://peps.python.org/pep-0518/) .

pyproject.toml is the newer format.
setup.py is the older format. 

Depending on what version of pip you are using you might get a different behavior here. With newer versions the installer will recognize the pyproject.toml file and use the meta data contained within to set up and execute installation. If this happens, any setup.py file and data contained within will be ignored. This is what was happening to Professor Brown. 

If you have an older pip version that does not recognize the PEP517/518 standard it will use the setup.py file for installation and ignore the pyproject.toml file.

I've gone ahead and updated both of these installation meta-data files to be up to date and consistent.

**Comment by davidhbrown** [comment]
@TimColaneri  (Hello again! I'm catching up on asteroid as I'll be teaching the second section of CSC 301 this semester.) 

Thank you for your knowledge of how python is packaged these days. In general, time has not been kind to PEP 20's idea that "there should be one -- and preferably only one -- obvious way to do it."
