### ISSUE TITLE
scientific notation for floating point values

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#34]
We need to extend Asteroid in order to support scientific notation for floating point values, e.g.
```
let v = 1.234E20.
```

**Comment by SupurCalvinHiggins** [comment]
Integers and reals are defined by the following regex:
```
([0-9]*[.])?[0-9]+
```
Scientific notation can be supported by allowing an optional suffix. 
```
([0-9]*[.])?[0-9]+(E\-?[0-9]+)?
```
This matches an integer or real and searches for an 'E', optional minus sign then another integer.
What do you think about this change?

As a side note, the current regex allows leading zeroes. Is this a bug or a feature?
