### ISSUE TITLE
patterns returned by functions used in pattern-matching contexts

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#40]
Asteroid should support something like the following,
```
function foo
   with *g() do -- g returns a pattern that we use in the with clause.
      <something>
  end
```
where patterns returned from functions should be able to be used in pattern matching contexts.
Another example,
```
let v = x is *goo().
```
The variable `v` is either true or false depending if the term stored in `x` matches the pattern returned 
by `goo` or not.

**Comment by olwmc** [comment]
If we're planning on allowing this, would we also want:

```
let v = x is *my_structure @ a.
let w = x is *my_structure @ foo().
```

**Comment by lutzhamel** [comment]
absolutely!  Basically, anything that can hold or return a value should be able to be dereferenced because it could be a pattern!
