### ISSUE TITLE
REPL feature

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#48]
We need to implement a read-evaluate-print-loop feature similar to what Python does.  

The tricky part here is how to integrate that with the frontend.  For example, in the Python REPL it knows exactly where you are in terms of syntax and will prompt you to complete the syntax for the current phrase.

**Comment by olwmc** [comment]
I've been doing some research on how we might go about doing this. It's not simple! But I'm learning quite a bit. I'll try to do a writeup once I get a good idea of how we might execute this.

**Comment by lutzhamel** [comment]
Excellent! Yes, it is not easy because a solution will be tightly integrated into the frontend/parser because it will need to recognize how much of a structure has been parsed and what else is needed.  Consider Python,
```
>>> for x in [1,2,3]:
...   <-- prompting for more input..
```
Similarly in SML,
```
ubuntu$ sml
Standard ML of New Jersey v110.79 [built: Sat Oct 26 12:27:04 2019]
- val x
= =1
= ;
val x = 1 : int
-
```

**Comment by olwmc** [comment]
Definitely not simple but there's a wealth of examples we can pull from. Currently on my reading list is the python repl, litecli, and probably a skim of how haskell manages it.

**Comment by olwmc** [comment]
I actually think asteroid provides an interesting pathway into exploring more context aware REPL's. The python repl is surprisingly... dumb?

Typing in something like
```python
>>> def d
```
And hitting tab for autocompletion brings up:
```bash
def del delattr( dict( dir( divmod(
```
Which would all, in their own way, either cause an error or rewrite a standard function!

**Comment by olwmc** [comment]
For an asteroid REPL, I think we should probably aim for behavior generally like:

```
function foo <tab> <tab>
```
Gives the autocomplete suggestions of *the only valid token in this scenario*, `with`.

**Comment by lutzhamel** [comment]
We could be very clever here, for example, we could list all the valid tokens that could appear next,
```
let x = <--- possible completions: ID, NUM, PAREN, BRACKET, ...
```
The parser knows exactly what it is parsing and therefore knows what the next tokens should be.

BUT, I am a strong believer in software evolution...build something and then make it better.  Because once you have something you learn a whole bunch of things that you couldn't predict and that learning process usually makes the software better compared to building something "perfect" from the start...but I am philosophizing.  Bottomline, the initial REPL can be really straightforward, it just keeps prompting the user until it has seen a completed sentence.  That is how sml does it: if you hit return before entering a complete sentence it simply keeps prompting...that would be sufficient for a first version.

**Comment by lutzhamel** [comment]
Sounds good to me! @olwmc you should also assign this to yourself...
