### ISSUE TITLE
Visibility of variables declared during a first-class pattern match

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#50]
Visibility of variables declared during a pattern match when using non-first-class patterns is usually not a problem, consider,
```
load system "io".

let (x,y) = (1,2). -- we can immediately see that the pattern match introduces x and y
println x.
println y.
```
Now consider using first-class patterns,
```
load system "io".

let P = pattern with (x,y).

-- lots of intervening code here...

let *P = (1,2). -- no longer obvious that the pattern match introduces x and y
println x.
println y.
```
Should there be explicit syntax such as,
```
let  x,y in *P  = (1,2).
```
indicating that the pattern match introduces variables x and y?

**Comment by olwmc** [comment]
Thinking of this issue: How does this notation scale?

Here's an example:
```
let (x, (y,z,a), b) = (1, ("xyz", 3,4), 5).
```
How would we make this pattern visible?

We could do sequential values, i.e. 
```
let ptrn = pattern with (x, (y,z,a), b).

let x1, y1, z1, a1, b1 in *ptrn = (1, ("xyz", 3,4), 5).
```
but I'm not sure how good this feels to write.

Using this syntax, though, you could do:
```
let x_2, y_2, z_2 in *ptrn = (1, ("xyz", 3,4), 5).

let (s, n_1, n_2) = y_2.
```
and deconstruct as you like.

**Comment by olwmc** [comment]
Thinking of this issue: How does this notation scale?

Here's an example of what I mean:
```
let ptrn = pattern with (x, (y,z,a), b).
```
How would we make this pattern visible?

We could do sequential values, i.e. when they appear in the pattern:
```
let x1, y1, z1, a1, b1 in *ptrn = (1, ("xyz", 3,4), 5).
```
but I'm not sure how good this feels to write.

**Comment by lutzhamel** [comment]
@olwmc @TimColaneri I am glad we are picking up this issue again.  And very apropos due the fact that Tim will be talking about this at the conference.  To take Oliver's example from above,
```
let ptrn = pattern with (x,(y,z,a),b).
```
the idea is that we spell out which variables are to be instantiated by the pattern.  In 99% of the cases we are NOT interested in all the variable values but only a select few and the other serve as anonymous structure matches like `%[x]%` or the anonymous variable `_`.  For example, I might only interested the values of `y`,`z`, and `a`,
```
let y,z,a in *ptrn = (1, ("xyz", 3,4), 5).
```
this would bind y->"xyz", z->3, and a->4 into the local environment but would ignore x and b.  The advantage is that the variables y,z, and a are explicitly declared in the local scope and don't just magically appear.  That this is a problem became clear in Tim's code.

I think the default behavior should still work, that is,
```
let *ptrn = (1, ("xyz", 3,4), 5).
```
will introduce the variables x, y, z, a, b with their bindings into the local environment.  The extension is there to make code more readable when patterns are non-local to the module.

Anyhow, those are my $0.02 🙂

**Comment by olwmc** [comment]
Ahh I see! That makes much more sense. Thanks!

**Comment by lutzhamel** [comment]
this issue has been superseded by #180.
