### ISSUE TITLE
module namespaces

### ISSUE THREAD

**Issue by lutzhamel** [asteroid-lang/asteroid#69]
We should probably support implicit namespaces for modules.  We could model something loosely after the Python module system: Each module comes with its own namespace and when loading it you can access declared entities in the module,
```
load system "io".
io @println "hello world!".
```
or you could specifically import declared entities from the module into your own namespace,
```
load system "io" import println.
println "hello world!".
```
or you could specifically import declared entities from the module into your own namespace under a different name,
```
load system "io" import println as foobaz.
foobaz "hello world!".
```
Importing `*` will make `load` work the way it is working right now,
```
load system "io" import *.
println "hello world!".
```
Interesting consequence of introducing namespaces for modules: module names become namespace qualifiers as in,
```
io @println "hello world".
```
What are the implications of this for the `load` statement?  I could see something like this,
```
load system "io".
```
is equivalent to
```
load system io.
```
where `io` is the name of the module.  The need for quotes is that this provides the ability to provide module paths,
```
load "mymodules/print".
print @println "hello world".
```

**Comment by lutzhamel** [comment]
I have implemented the io module as an object to address the concerns of this issue. The hello world program works now as,
```
load system io.
io @println "Hello, World!".
```
Since objects have their own scope the will be no clash with function/member names of other modules making the other suggestions above superfluous.

In particular I dislike the Python like statement
```
load system io import println.
println "hello world!".
```
which would import a name into the current name space without being able to trace to where it came from.  The scoped version of the module import is much cleaner because you are not allowed to clutter your current name space with duplicates from the object name space.

Take a peek at the io.ast module on the issue-69 branch.  I would be very interested to hear your thoughts. If this is acceptable then I will convert all the other modules to objects as well.

**Comment by olwmc** [comment]
Looks great!!
